### ISSUE TITLE
not compatiblw with astro 4.16.*

### ISSUE THREAD

**Issue by saiballo** [jasikpark/astro-svg-loader#129]
Hello,

Have you planned to migrate the plugin to the latest versions of Astro?

thank you

**Comment by jasikpark** [comment]
I just published [0.3.0](https://github.com/jasikpark/astro-svg-loader/blob/main/CHANGELOG.md#030) which sets Astro 4 as a peer dep. Does that solve your issue? I have no issues using the tool with Astro 4.16.6

**Comment by saiballo** [comment]
thank you so much!!! It works

**Comment by jasikpark** [comment]
Great! Glad to hear 💜
