### ISSUE TITLE
Has some way to use it in preact ?

### ISSUE THREAD

**Issue by vaynevayne** [jasikpark/astro-svg-loader#53]
not work in preact file ,

```jsx

import Svg from "astro-svg-loader"
import map3Svg from "@assets/map3.svg"

 <Svg
          src={import("@assets/map3Svg.svg?raw")}
          aria-label="Cool illustration of an abstract nebula"
        />
```

**Comment by jasikpark** [comment]
hmm yeah I think you'd need to use something like https://react-svgr.com/ for that -- this is specifically a tool for Astro components -- maybe I should make that clearer in the readme - I'm not sure if I could make that work for preact. 

What error do you get?

**Comment by jasikpark** [comment]
this is a solution only for astro components, if you want to use it w/ preact, maybe try passing the svg in via a slot?
