### ISSUE TITLE
Usage in Astro component

### ISSUE THREAD

**Issue by kireerik** [jasikpark/astro-svg-loader#55]
Not working when I am trying to use it in an Astro component (which is outside of the root Astro directory).

Using it directly in an Astro page works (using a relative path (Trying to use the `@assets/` syntax it does not work (not even in an Astro page).)).

**Comment by kireerik** [comment]
- https://github.com/jasikpark/astro-svg-loader/issues/56#issuecomment-1557896280

**Comment by jasikpark** [comment]
is your project open source? mind providing a repro? https://astro.new/minimal?on=stackblitz

**Comment by kireerik** [comment]
I am now using [astro-svg-components](https://github.com/MrFoxPro/astro-svg-components). That works properly.

**Comment by jasikpark** [comment]
Ok, are you not interested in fixing your setup w/ `@jasikpark/astro-svg-loader`? I can close your issues? 

Happy to help sort it out otherwise

**Comment by kireerik** [comment]
Yes [astro-svg-components](https://github.com/MrFoxPro/astro-svg-components). seems to work well for me, and I actually prefer it's structure in terms of the usage I think.
