### ISSUE TITLE
Causes `astro build` to fail

### ISSUE THREAD

**Issue by kireerik** [jasikpark/astro-svg-loader#56]
The error says it `Could not resolve` the svg.

&nbsp;
> Resolution works fine in development mode.

**Comment by kireerik** [comment]
[astro-svg-components](https://github.com/MrFoxPro/astro-svg-components) works properly. (So I am using that instead.)

**Comment by kireerik** [comment]
Seems like [astro-svg-components](https://github.com/MrFoxPro/astro-svg-components) has a similar issue:
- #1

**Comment by jasikpark** [comment]
mind making a reproduction for one of these w/ https://astro.new? I'd definitely look into it

**Comment by kireerik** [comment]
With [astro-svg-components](https://github.com/MrFoxPro/astro-svg-components)?

**Comment by jasikpark** [comment]
sure 🤷

**Comment by kireerik** [comment]
On StackBlitz installing the module is not working. On CodeSandbox I can not reproduce the issue, however I do not see the build output, because only the build folder is created, but it is empty. So I can not check the output there.

**Comment by kireerik** [comment]
- https://codesandbox.io/p/sandbox/affectionate-microservice-xtm7j0?file=%2Fsite%2Findex%2Findex.astro%3A2%2C32

**Comment by kireerik** [comment]
Maybe the above CodeSandbox can help to reproduce the issue locally.

**Comment by kireerik** [comment]
https://github.com/MrFoxPro/astro-svg-components/issues/1#issuecomment-1561988522

**Comment by kireerik** [comment]
I was able to reproduce the issue:
- https://github.com/MrFoxPro/astro-svg-components/issues/1#issuecomment-1562006426

**Comment by kireerik** [comment]
Using the following function works:
```Node.js
const importSvg = name => import(`./${name}.svg?raw`)
```

However if I separate this function into a separate module and import it and use it like that. That does not work.

@jasikpark Would you expect this to work (even when using it from a separate module (as explained above)) or this is the same Astro limitation (https://github.com/MrFoxPro/astro-svg-components/issues/1#issuecomment-1562177826)?

**Comment by jasikpark** [comment]
hmm I think that's a limitation of Vite/Astro, yeah - my Svg component just awaits a dynamic import and uses whatever you imported as an svg...
